[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Sanion"
version = "0.1.0"
dependencies = [
    "rich",
    "cryptography",
    "python-dotenv",
    "typer[all]"
]