name: Code Analysis

on: [push, pull_request]

jobs:
  lint_and_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flake8 bandit pytest

      - name: Run Flake8 (Linting)
        run: flake8 .

      - name: Run Bandit (Security check)
        run: bandit -r .

